version: '3.1'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306