spring:
  config:
    import:
      - classpath:/application-local.yml
logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error