spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost/chatting
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
